sudo: false
language: node_js
services:
- redis-server
node_js:
- stable
- "lts/*"
- 6
env:
  matrix:
  - CMD=lint
  - CMD=test
script:
- npm run $CMD
after_success:
- '[ "$CMD" == "test" ] && npm run coverage'
notifications:
  email: false
